import type { Metadata } from "next";
import "./globals.css";
import { CoreInitializer } from "@repo/core-next/client";
import { api } from "@repo/core-next/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SITE_ID = "a";

api.initCore(SITE_ID);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <CoreInitializer siteId={SITE_ID} />
        {children}
      </body>
    </html>
  );
}
