import "./globals.css";

import { CoreBootstrap } from "@repo/core-next/bootstrap";
import type { Metadata } from "next";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SITE_ID = "a";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <CoreBootstrap siteId={SITE_ID} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
